ENH/jhr: adopt lvm to work as replacement for env previously with gfs2clvm

diff --git a/src/datastore_mad/remotes/lvm/stat b/src/datastore_mad/remotes/lvm/stat
--- a/src/datastore_mad/remotes/lvm/stat
+++ b/src/datastore_mad/remotes/lvm/stat
@@ -1,1 +1,80 @@
-../common/stat
+#!/bin/bash
+
+# -------------------------------------------------------------------------- #
+# Copyright 2002-2013, OpenNebula Project (OpenNebula.org), C12G Labs        #
+#                                                                            #
+# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
+# not use this file except in compliance with the License. You may obtain    #
+# a copy of the License at                                                   #
+#                                                                            #
+# http://www.apache.org/licenses/LICENSE-2.0                                 #
+#                                                                            #
+# Unless required by applicable law or agreed to in writing, software        #
+# distributed under the License is distributed on an "AS IS" BASIS,          #
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
+# See the License for the specific language governing permissions and        #
+# limitations under the License.                                             #
+#--------------------------------------------------------------------------- #
+
+# ------------------------------------------------------------------------------
+#  Set up Environment and transfer arguments
+# ------------------------------------------------------------------------------
+#
+#  vmfs.conf: includes default TMP_DIR
+#  libfs.sh a& scripts_common.sh: includes tools and lib calls
+# ------------------------------------------------------------------------------
+
+if [ -z "${ONE_LOCATION}" ]; then
+    LIB_LOCATION=/usr/lib/one
+else
+    LIB_LOCATION=$ONE_LOCATION/lib
+fi
+
+. $LIB_LOCATION/sh/scripts_common.sh
+
+DRIVER_PATH=$(dirname $0)
+source ${DRIVER_PATH}/../libfs.sh
+source ${DRIVER_PATH}/lvm.conf
+
+# -------- Get stat and datastore arguments from OpenNebula core ------------
+
+DRV_ACTION=$1
+ID=$2
+
+XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"
+
+unset i XPATH_ELEMENTS
+
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <($XPATH /DS_DRIVER_ACTION_DATA/IMAGE/PATH)
+
+SRC="${XPATH_ELEMENTS[0]}"
+
+# ------------------------------------------------------------------------------
+#  Compute the size
+# ------------------------------------------------------------------------------
+
+log "$(hostname -f)"
+
+SIZE=`fs_size $SRC`
+
+set -x
+
+STAT_CMD=$(cat <<EOF
+set -ex
+stat -c %s $SRC
+EOF
+)
+
+if [ "$SIZE" = "0" ]; then
+    ssh_exec_and_log "$HOST" "$STAT_CMD" \
+       "Error getting remote file size"
+fi
+
+if [ "$SIZE" = "0" ]; then
+    log_error "Cannot determine size for $SRC"
+    exit -1
+fi
+
+echo "$SIZE"
